import {JSDOM} from 'jsdom';import {build} from '../apps/web/node_modules/esbuild/lib/main.js';import assert from 'node:assert/strict';
import {fixture,ids,shutdown} from './reply-fixture.mjs';
const dom=new JSDOM('<html><body></body></html>',{url:'https://local.invalid/item/'+ids.item});
for(const key of ['window','document','HTMLElement','MutationObserver'])globalThis[key]=dom.window[key];
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let active,sendCount=0,sentNotices=0,holdCheck=null,sendTimeout=false,apiCalls=[];
globalThis.Deno={env:{get:()=> 'true'}};
globalThis.__db={rpc:async(name,args)=>{assert.equal(name,'mcc_reply_command');try{return {data:await active.command(args.p_operation,args.p_input,args.p_actor),error:null};}catch(e){return {data:null,error:{message:e.message}};}}};
const reviewBundle=await build({entryPoints:['supabase/functions/api/reply-review.ts'],bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'auth-boundary',setup(b){b.onResolve({filter:/(?:_shared\/)?util\.ts$/},()=>({path:'util',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:`export class HttpError extends Error{constructor(status,message){super(message);this.status=status;}};export const handleOptions=()=>null;export const json=(body,status=200)=>new Response(JSON.stringify(body),{status});export const serviceClient=()=>globalThis.__db;export const requireUser=async()=>({userId:'${ids.user}'});`}));}}]});
const review=(await import('data:text/javascript;base64,'+Buffer.from(reviewBundle.outputFiles[0].text).toString('base64'))).default;
globalThis.__api=async(route,body)=>{apiCalls.push({route,body});if(route==='gmail-get-body'){assert.equal(body.message_id,ids.message);await active.db.query('update messages set body_text=$1 where id=$2',['The full source is now loaded.',ids.message]);return {body:'The full source is now loaded.'};}if(route==='reply-review'){const r=await review(new Request('https://local.invalid/api/reply-review',{method:'POST',body:JSON.stringify(body)}));const data=await r.json();if(!r.ok)throw Error(data.error);if(body.operation==='CHECK'&&holdCheck)await holdCheck;return data;}assert.equal(route,'gmail-send');const reserved=await active.command('RESERVE',{approval_id:body.approval_id,channel:'email'});if(reserved.existing)return reserved;const started=await active.command('BEGIN',{dispatch_id:reserved.dispatch_id,channel:'email'});sendCount++;if(sendTimeout)throw Error('response interrupted');await active.command('FINISH',{dispatch_id:started.dispatch_id,status:'SENT',provider_id:'synthetic-ui'});return {dispatch_id:started.dispatch_id,status:'SENT'};};
const ui=await build({entryPoints:['apps/web/src/components/ReplyReview.tsx'],bundle:true,write:false,format:'esm',platform:'node',jsx:'automatic',plugins:[{name:'ui-boundary',setup(b){b.onResolve({filter:/lib\/supabase$/},()=>({path:'api',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const api=(...args)=>globalThis.__api(...args);'}));b.onResolve({filter:/^react(\/.*)?$/},a=>({path:'file://'+process.cwd()+'/node_modules/react/'+(a.path==='react'?'index.js':a.path.slice(6)+'.js'),external:true}));}}]});
const Component=(await import('data:text/javascript;base64,'+Buffer.from(ui.outputFiles[0].text).toString('base64'))).default;
const React=(await import('react')).default;const {render,screen,fireEvent,waitFor,cleanup}=await import('@testing-library/react');
async function reset(){cleanup();active=await fixture();sendCount=0;sentNotices=0;sendTimeout=false;holdCheck=null;apiCalls=[];render(React.createElement(Component,{itemId:ids.item,channel:'email',onSent:()=>sentNotices++}));}
const edit=text=>fireEvent.change(screen.getByRole('textbox',{name:'Reply text'}),{target:{value:text}});
const click=name=>fireEvent.click(screen.getByRole('button',{name,exact:true}));
async function check(){await waitFor(()=>assert.ok(!screen.getByRole('button',{name:'Save and check evidence'}).disabled));click('Save and check evidence');await screen.findByText('Sources support the mapped claims; full review still required');await waitFor(()=>assert.ok(!screen.getByRole('button',{name:'Save and check evidence'}).disabled));}
async function approve(){fireEvent.click(screen.getByLabelText(/I reviewed the entire reply/));click('Approve this exact reply');await waitFor(()=>assert.ok(!screen.getByRole('button',{name:'Send approved reply'}).disabled));}
// Full price/evidence/review/approval/dispatch path against the actual handler and SQL.
await reset();edit('It costs $1250.');click('Save and check evidence');await screen.findByText('Resolve evidence issues before approval');
assert.ok(screen.getByRole('button',{name:'Send approved reply'}).disabled);
fireEvent.change(screen.getByRole('textbox',{name:'Claim value 1'}),{target:{value:'USD:125000'}});
fireEvent.change(screen.getByRole('combobox',{name:'Source 1'}),{target:{value:ids.message}});
fireEvent.change(screen.getByRole('textbox',{name:'Source excerpt 1'}),{target:{value:'$1250'}});
fireEvent.click(screen.getByLabelText(/I verified this source supports/));click('Record reviewed evidence');
await screen.findByText('Evidence linked. Save and check again before approval.');await check();await approve();
click('Send approved reply');click('Send approved reply');await screen.findByText('Delivery: sent');assert.equal(sendCount,1);assert.equal(sentNotices,1);
assert.ok(screen.getByRole('textbox',{name:'Reply text'}).disabled);
// Every edit, including a revert, clears approval.
await reset();edit('Thank you.');await check();await approve();edit('Thank you!');edit('Thank you.');assert.ok(screen.getByRole('button',{name:'Send approved reply'}).disabled);assert.equal(screen.queryByText(/Approval expires at/),null);
// Stale response cannot resurrect an older check/approval after an edit.
await reset();edit('Thank you.');let release;holdCheck=new Promise(r=>release=r);click('Save and check evidence');await waitFor(()=>assert.ok(apiCalls.some(c=>c.body.operation==='CHECK')));edit('New reply');await React.act(async()=>{release();holdCheck=null;});assert.equal(screen.getByRole('textbox',{name:'Reply text'}).value,'New reply');assert.equal(screen.queryByText('Sources support the mapped claims; full review still required'),null);assert.ok(screen.getByRole('button',{name:'Send approved reply'}).disabled);
// Interrupted send preserves a status lookup by approval, never a second send action.
await reset();edit('Thank you.');await check();await approve();sendTimeout=true;click('Send approved reply');await screen.findByText('Delivery: unknown');assert.ok(screen.getByRole('button',{name:'Send approved reply'}).disabled);click('Check delivery status');await screen.findByText('Delivery: sending');assert.equal(sendCount,1);assert.ok(apiCalls.some(c=>c.body.operation==='STATUS'&&c.body.approval_id));
// Missing metadata-only bodies must be loaded explicitly and checked again.
await reset();await active.db.exec('update messages set body_text=null');edit('Thank you.');click('Save and check evidence');await screen.findByText('Resolve evidence issues before approval');await waitFor(()=>assert.ok(!screen.getByRole('button',{name:'Load next 1 missing source bodies'}).disabled));click('Load next 1 missing source bodies');await waitFor(()=>assert.ok(screen.queryByRole('button',{name:'Load next 1 missing source bodies'})===null));await check();assert.equal(apiCalls.filter(c=>c.route==='gmail-get-body').length,1);
// A new item mount cannot inherit previous text, source metadata, or approval.
cleanup();render(React.createElement(Component,{itemId:ids.other,channel:'email',initialDraft:{itemId:ids.item,id:ids.draft,text:'FOREIGN CLIENT DRAFT',revision:1},onSent:()=>{}}));assert.equal(screen.getByRole('textbox',{name:'Reply text'}).value,'');assert.ok(screen.getByRole('button',{name:'Send approved reply'}).disabled);
cleanup();await shutdown();dom.window.close();console.log('PASS: 6 integrated UI scenarios: explicit source-body loading; price evidence through dispatch; edit/revert invalidation; stale check response; interrupted-send lookup; item isolation');
