// Chromium -> exact ReplyReview component -> exact Edge routes -> native DB.
// Only the transport adapter and surrounding fixture page are test-specific.
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import http from 'node:http';import assert from 'node:assert/strict';import {build} from '../apps/web/node_modules/esbuild/lib/main.js';import {chromium} from 'playwright';
import {url,anon,seed,sql} from './reply-native-helpers.mjs';
const {owner}=JSON.parse(fs.readFileSync(process.env.REPLY_BROWSER_AUTH,'utf8'));
const evidence=process.env.REPLY_EVIDENCE,dir=fs.mkdtempSync(path.join(os.tmpdir(),'reply-browser-'));
const fixture={item:seed(owner.id),channel:'email',disabled:false,foreign:false};
const api=`export async function api(route,body){const config=globalThis.__fixture;const r=await fetch(config.url+'/functions/v1/'+(config.disabled?'reply-disabled':'reply-runtime')+'/'+route,{method:'POST',headers:{apikey:config.anon,authorization:'Bearer '+config.token,'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}`;
const entry=`import React from 'react';import {createRoot} from 'react-dom/client';import ReplyReview from './apps/web/src/components/ReplyReview.tsx';const c=globalThis.__fixture;createRoot(document.getElementById('root')).render(<main className="max-w-3xl mx-auto p-4"><h1 className="text-xl font-bold mb-4">Review reply</h1><ReplyReview itemId={c.item.item} channel={c.channel} initialDraft={c.foreign?{itemId:'00000000-0000-4000-8000-000000000099',id:'00000000-0000-4000-8000-000000000098',text:'FOREIGN CLIENT TEXT',revision:1}:null} onSent={()=>{}}/></main>);`;
let replacements=0;
await build({stdin:{contents:entry,resolveDir:process.cwd(),loader:'tsx'},bundle:true,format:'esm',platform:'browser',jsx:'automatic',outfile:path.join(dir,'app.js'),plugins:[{name:'local-only-transport',setup(b){b.onResolve({filter:/lib\/supabase$/},()=>({path:'api',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>{replacements++;return {contents:api};});}}]});assert.equal(replacements,1);
const css=fs.readdirSync('apps/web/dist/assets').filter(n=>n.endsWith('.css'));assert.equal(css.length,1);fs.copyFileSync('apps/web/dist/assets/'+css[0],path.join(dir,'style.css'));
const server=http.createServer((req,res)=>{if(req.url==='/app.js'||req.url==='/style.css'){res.setHeader('content-type',req.url.endsWith('.js')?'text/javascript':'text/css');res.end(fs.readFileSync(path.join(dir,req.url.slice(1))));return;}
 res.setHeader('content-type','text/html');res.end('<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/style.css"><body><div id="root"></div><script>globalThis.__fixture='+JSON.stringify({url,anon,token:owner.token,...fixture}).replaceAll('<','\\u003c')+'</script><script type="module" src="/app.js"></script></body></html>');});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:1000}});const errors=[],blocked=[];
page.on('pageerror',e=>errors.push(String(e)));await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.protocol==='http:'&&u.hostname==='127.0.0.1')return route.continue();blocked.push(u.origin);return route.abort();});
const button=name=>page.getByRole('button',{name,exact:true});
const waitText=async text=>page.getByText(text,{exact:true}).waitFor();
const open=async(channel='email',disabled=false,foreign=false)=>{fixture.item=seed(owner.id,channel);fixture.channel=channel;fixture.disabled=disabled;fixture.foreign=foreign;await page.goto(base+'/item/'+fixture.item.item);await page.getByRole('textbox',{name:'Reply text'}).waitFor();};
const edit=text=>page.getByRole('textbox',{name:'Reply text'}).fill(text);
async function check(){await button('Save and check evidence').click();await waitText('Sources support the mapped claims; full review still required');}
async function approve(){await page.getByLabel(/I reviewed the entire reply/).check();await button('Approve this exact reply').click();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Send approved reply'&&!b.disabled));}
try{
 await page.goto(base);await edit('It costs $1250.');await button('Save and check evidence').click();await waitText('Resolve evidence issues before approval');assert(await button('Send approved reply').isDisabled());
 await page.getByRole('textbox',{name:'Claim value 1'}).fill('USD:125000');await page.getByRole('combobox',{name:'Source 1'}).selectOption(fixture.item.message);await page.getByRole('textbox',{name:'Source excerpt 1'}).fill('$1250');await page.getByLabel(/I verified this source supports/).check();await button('Record reviewed evidence').click();await waitText('Evidence linked. Save and check again before approval.');await check();
 await page.screenshot({path:path.join(evidence,'review-supported-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(evidence,'review-supported-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No mobile horizontal overflow');await page.setViewportSize({width:1280,height:1000});
 await approve();await button('Send approved reply').click();await waitText('Delivery: sent');assert(await page.getByRole('textbox',{name:'Reply text'}).isDisabled());assert.equal(sql(`select count(*) from reply_dispatches where payload->>'queueItemId'='${fixture.item.item}' and status='SENT';`),'1');
 console.log('PASS: price source/review/exact approval/synthetic send, desktop and mobile screenshots');
 await open();await edit('Thank you.');await check();await approve();await edit('Thank you!');await edit('Thank you.');assert(await button('Send approved reply').isDisabled());console.log('PASS: edit/revert clears approval');
 await open('sms');await edit('Thank you.');await check();await approve();await button('Send approved reply').click();await waitText('Delivery: sent');console.log('PASS: actual SMS review and route');
 await open('email',true);await edit('Thank you.');await check();await page.getByLabel(/I reviewed the entire reply/).check();await button('Approve this exact reply').click();await page.getByText(/Approval expires at/).waitFor();assert(await button('Send approved reply').isDisabled());await waitText('Sending is disabled in this environment. Review and approval can still be tested.');console.log('PASS: default-off UI gate');
 await open();await edit('Thank you.');await check();await approve();
 await page.route('**/functions/v1/reply-runtime/gmail-send',async route=>{await route.fetch();await route.abort('failed');},{times:1});await button('Send approved reply').click();await waitText('Delivery: unknown');assert(await button('Send approved reply').isDisabled());await button('Check delivery status').click();await waitText('Delivery: sent');assert.equal(sql(`select count(*) from reply_dispatches where payload->>'queueItemId'='${fixture.item.item}';`),'1');console.log('PASS: interrupted send response recovers status without another send');
 await open('email',false,true);assert.equal(await page.getByRole('textbox',{name:'Reply text'}).inputValue(),'');assert(!(await page.content()).includes('FOREIGN CLIENT TEXT</textarea>'));await page.goBack();assert(await button('Send approved reply').isDisabled());await page.goForward();assert(await button('Send approved reply').isDisabled());console.log('PASS: foreign initial draft and browser back/forward cannot restore approval');
 assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);fs.writeFileSync(path.join(evidence,'browser-summary.json'),JSON.stringify({scenarios:6,pageErrors:errors,blockedEgress:blocked,browser:browser.version(),surface:'Exact ReplyReview component, fixture shell/local transport, native Auth/PostgREST/Edge'},null,2));
}finally{await browser.close();await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
