// Actual ItemDetail, hooks, router, QueryClient and ReplyReview against native REST/Edge.
// Login is supplied by the throwaway native Auth user. Draft generation alone is synthetic.
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import http from 'node:http';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {build} from '../apps/web/node_modules/esbuild/lib/main.js';import {chromium} from 'playwright';
import {url,anon,seed,sql,quote} from './reply-native-helpers.mjs';
const {owner}=JSON.parse(fs.readFileSync(process.env.REPLY_BROWSER_AUTH,'utf8')),evidence=process.env.REPLY_EVIDENCE;
const a=seed(owner.id),b=seed(owner.id,'sms');
const run=randomUUID(),artifact=randomUUID(),strategy=randomUUID();
sql(`insert into pipeline_runs(id,user_id,contact_id,business_id,status,analyze_request) values('${run}','${owner.id}','${a.contact}','${a.business}','complete','{}');
insert into pipeline_artifacts(id,user_id,run_id,contact_id,stage,prompt_id,input_schema_version,output_schema_version,input,output,provider,model) values('${artifact}','${owner.id}','${run}','${a.contact}',3,'fixture','fixture','fixture','{}','{"recommended_approach":"Synthetic reviewed strategy"}','synthetic','none');
insert into contact_strategies(id,user_id,contact_id,business_id,comm_artifact_id,allowed_zone) values('${strategy}','${owner.id}','${a.contact}','${a.business}','${artifact}','yellow');
insert into reply_drafts(id,user_id,queue_item_id,draft_text,confidence) values('${a.draft}','${owner.id}','${a.item}','Synthetic generated reply.','yellow');`);
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reply-item-detail-'));
const adapter=`import {createClient} from '@supabase/supabase-js';const c=globalThis.__fixture;export const supabase=createClient(c.url,c.anon,{auth:{persistSession:false},global:{headers:{Authorization:'Bearer '+c.token}}});export async function api(route,body){if(route==='draft-reply'){return new Promise(resolve=>globalThis.__resolveDraft=()=>resolve({queue_item_id:c.a.item,draft_id:c.a.draft,revision:1,draft:'Synthetic generated reply.',notes:'Fixture boundary; no model call',verification_needed:[]}));}if(!['reply-review','gmail-send','twilio-send','gmail-get-body'].includes(route))throw Error('Unexpected fixture action '+route);const r=await fetch(c.url+'/functions/v1/reply-runtime/'+route,{method:'POST',headers:{apikey:c.anon,authorization:'Bearer '+c.token,'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}`;
const entry=`import React from 'react';import {createRoot} from 'react-dom/client';import {BrowserRouter,Routes,Route,Link} from 'react-router-dom';import {QueryClient,QueryClientProvider} from '@tanstack/react-query';import ItemDetail from './src/pages/ItemDetail.tsx';const c=globalThis.__fixture;createRoot(document.getElementById('root')).render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false,staleTime:0}}})}><BrowserRouter><nav aria-label="Fixture navigation"><Link to={'/item/'+c.a.item}>Fixture email</Link> | <Link to={'/item/'+c.b.item}>Fixture SMS</Link></nav><Routes><Route path="/item/:id" element={<ItemDetail/>}/></Routes></BrowserRouter></QueryClientProvider>);`;
await build({stdin:{contents:entry,resolveDir:path.resolve('apps/web'),loader:'tsx'},bundle:true,format:'esm',platform:'browser',jsx:'automatic',outfile:path.join(dir,'app.js'),plugins:[{name:'native-local-transport',setup(build){build.onResolve({filter:/lib\/supabase$|^\.\/supabase$/},()=>({path:'api',namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:adapter,resolveDir:path.resolve('apps/web')}));}}]});
const css=fs.readdirSync('apps/web/dist/assets').find(p=>p.endsWith('.css'));fs.copyFileSync('apps/web/dist/assets/'+css,path.join(dir,'style.css'));
const server=http.createServer((req,res)=>{if(['/app.js','/style.css'].includes(req.url)){res.setHeader('content-type',req.url.endsWith('.js')?'text/javascript':'text/css');res.end(fs.readFileSync(path.join(dir,req.url.slice(1))));return;}res.setHeader('content-type','text/html');res.end('<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"><body><div id="root"></div><script>globalThis.__fixture='+JSON.stringify({url,anon,token:owner.token,a,b}).replaceAll('<','\\u003c')+'</script><script type="module" src="/app.js"></script></body></html>');});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[],blocked=[];
page.on('pageerror',e=>errors.push(String(e)));await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.protocol==='http:'&&u.hostname==='127.0.0.1')return r.continue();blocked.push(u.origin);return r.abort();});
const button=name=>page.getByRole('button',{name,exact:true});const reply=()=>page.getByRole('textbox',{name:'Reply text'});
const waitItem=async item=>{await page.waitForURL('**/item/'+item.item);await page.locator('a[href="/contacts/'+item.contact+'"]').first().waitFor();await reply().waitFor();};
try{
 await page.goto(base+'/item/'+a.item);await waitItem(a);await page.getByText('The price is $1250.',{exact:true}).waitFor();
 await button('Draft reply using strategy').click();await page.waitForFunction(()=>typeof globalThis.__resolveDraft==='function');await page.getByRole('link',{name:'Fixture SMS'}).click();await waitItem(b);await page.evaluate(()=>globalThis.__resolveDraft());await page.waitForTimeout(100);assert.equal(await reply().inputValue(),'');assert.equal(await page.getByText('Strategy draft',{exact:true}).count(),0);console.log('PASS: late generated draft never crosses ItemDetail client navigation');
 await page.getByRole('link',{name:'Fixture email'}).click();await waitItem(a);await page.waitForFunction(()=>document.querySelector('textarea[aria-label="Reply text"]')?.value==='Synthetic generated reply.');assert(await button('Send approved reply').isDisabled());
 await button('Save and check evidence').click();await page.getByText('Sources support the mapped claims; full review still required',{exact:true}).waitFor();await page.getByLabel(/I reviewed the entire reply/).check();await button('Approve this exact reply').click();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Send approved reply'&&!b.disabled));
 await page.screenshot({path:path.join(evidence,'item-detail-approved-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(evidence,'item-detail-approved-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.getByRole('link',{name:'Fixture SMS'}).click();await waitItem(b);assert.equal(await reply().inputValue(),'');assert(await button('Send approved reply').isDisabled());await page.goBack();await waitItem(a);assert(await button('Send approved reply').isDisabled());console.log('PASS: full ItemDetail navigation and Back invalidate approval and isolate draft');
 await page.getByRole('link',{name:'Fixture SMS'}).click();await waitItem(b);await reply().fill('Thank you.');await button('Save and check evidence').click();await page.getByLabel(/I reviewed the entire reply/).check();await button('Approve this exact reply').click();await button('Send approved reply').click();await page.getByText('Delivery: sent',{exact:true}).waitFor();await page.locator('span').filter({hasText:/^responded$/}).waitFor();assert.equal(sql(`select count(*) from reply_dispatches where payload->>'queueItemId'=${quote(b.item)} and status='SENT';`),'1');console.log('PASS: full ItemDetail manual SMS passes the same persisted gate');
 assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);fs.writeFileSync(path.join(evidence,'item-detail-browser-summary.json'),JSON.stringify({scenarios:3,pageErrors:errors,blockedEgress:blocked,surface:'Actual ItemDetail/hooks/router/queries/review/send against native REST/Edge; synthetic draft-generation boundary only'},null,2));
}finally{await browser.close();await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
