import test from 'node:test';import assert from 'node:assert/strict';
import {build} from '../apps/web/node_modules/esbuild/lib/main.js';
import {fixture,ids,shutdown} from './reply-fixture.mjs';
let active,enabled=true,providerMode='ok',ingestFails=false,providerCalls=[],secretCalls=0;
globalThis.Deno={env:{get:()=>enabled?'true':'false'}};
globalThis.__db={rpc:async(name,args)=>{if(name==='mcc_reply_command'){try{return {data:await active.command(args.p_operation,args.p_input,args.p_actor),error:null};}catch(e){return {data:null,error:{message:e.message}};}}if(name.startsWith('ingest_'))return {data:{},error:ingestFails?{message:'synthetic ingestion failure'}:null};throw Error('unexpected RPC '+name);},from:table=>{const filters={};const query={select:()=>query,eq:(k,v)=>{filters[k]=v;return query;},maybeSingle:async()=>{assert.ok(['gmail_accounts','twilio_numbers'].includes(table));return {data:(await active.db.query(`select * from ${table} where id=$1 and user_id=$2`,[filters.id,filters.user_id])).rows[0]??null,error:null};}};return query;}};
globalThis.__secret=()=>{secretCalls++;return 'SYNTHETIC_NOT_A_SECRET';};
globalThis.__gmailPost=async(_token,_path,payload)=>{providerCalls.push({channel:'email',payload});if(providerMode==='throw')throw Error('synthetic timeout');return providerMode==='malformed'?{}:{id:'synthetic-email-1'};};
globalThis.fetch=async(url,options)=>{assert.match(String(url),/^https:\/\/api\.twilio\.com\//);providerCalls.push({channel:'phone',payload:String(options.body)});if(providerMode==='throw')throw Error('synthetic timeout');return new Response(JSON.stringify(providerMode==='malformed'?{}:{sid:'synthetic-sms-1'}),{status:200});};
async function bundle(path){const r=await build({entryPoints:[path],bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'test-boundary',setup(b){b.onResolve({filter:/(?:_shared\/)?(util|gmail)\.ts$/},a=>({path:a.path.includes('gmail')?'gmail':'util',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='util'?`
export class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
export const handleOptions=r=>r.method==='OPTIONS'?new Response(null,{status:204}):null;
export const json=(v,status=200)=>new Response(JSON.stringify(v),{status});
export const serviceClient=()=>globalThis.__db;
export const requireUser=async r=>{const t=r.headers.get('authorization');if(t!=='Bearer owner'&&t!=='Bearer foreign')throw new HttpError(401,'unauthorized');return {userId:t==='Bearer owner'?'${ids.user}':'${ids.other}'};};
export const getUserSecret=async()=>globalThis.__secret();`:`export const accessTokenForAccount=async()=>globalThis.__secret();export const gmailPost=globalThis.__gmailPost;export const gmailJson=async()=>({id:'synthetic-email-1',threadId:'provider-thread'});export const metadataQuery=()=>'';export const buildIngestPayload=()=>({synthetic:true});` }));}}]});return (await import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'))).default;}
const review=await bundle('supabase/functions/api/reply-review.ts'),gmail=await bundle('supabase/functions/api/gmail-send.ts'),twilio=await bundle('supabase/functions/api/twilio-send.ts');
export async function request(handler,body,token='owner',method='POST'){const res=await handler(new Request('https://local.invalid/api/reply-review',{method,headers:token?{authorization:`Bearer ${token}`}:{},...(method==='POST'?{body:JSON.stringify(body)}:{})}));return {status:res.status,body:await res.json()};}
async function setup(channel='email'){active=await fixture();enabled=true;providerMode='ok';ingestFails=false;providerCalls=[];secretCalls=0;if(channel!=='email')await active.db.exec(`insert into twilio_numbers values('${ids.account}','${ids.user}','+15550000001','active');update threads set channel='${channel}',gmail_account_id=null,twilio_number_id='${ids.account}',provider_thread_id='${channel}:+15550000002';update queue_items set channel='${channel}',sender_identifier='+15550000002';update messages set channel='${channel}',from_identifier='+15550000002',gmail_account_id=null,twilio_number_id='${ids.account}';`);const saved=await request(review,{operation:'SAVE',queue_item_id:ids.item,draft_id:ids.draft,revision:0,text:'Thank you.',claims:[],user_id:ids.other});assert.equal(saved.status,200);return saved.body;}
async function approve(){const c=await request(review,{operation:'CHECK',draft_id:ids.draft});assert.equal(c.status,200,JSON.stringify(c));assert.equal(c.body.check.status,'SOURCE_SUPPORTED_REQUIRES_REVIEW',JSON.stringify(c));const a=await request(review,{operation:'APPROVE',check_id:c.body.check_id,snapshot_key:c.body.check.snapshotKey,review_key:c.body.check.reviewKey,coverage_reviewed:true});assert.equal(a.status,200);return a.body;}
for(const channel of ['email','sms','whatsapp'])test(`actual ${channel} route + SQL dispatch uses exact stored payload, ignores request text and sends once`,async()=>{await setup(channel);const a=await approve();const handler=channel==='email'?gmail:twilio;const sent=await request(handler,{approval_id:a.approval_id,channel,body:'INJECTED',queue_item_id:ids.other});assert.equal(sent.status,200);assert.equal(sent.body.status,'SENT',JSON.stringify(sent));assert.equal(providerCalls.length,1);const payload=channel==='email'?Buffer.from(providerCalls[0].payload.raw,'base64url').toString():new URLSearchParams(providerCalls[0].payload).get('Body');assert.match(payload,/Thank you\./);assert.doesNotMatch(payload,/INJECTED/);const again=await request(handler,{approval_id:a.approval_id,channel});assert.equal(again.body.existing,true);assert.equal(providerCalls.length,1);const status=await request(review,{operation:'STATUS',approval_id:a.approval_id});assert.equal(status.body.ingestion_pending,false);});
test('method/auth/old sentinel/malformed input/foreign actor cannot reach provider',async()=>{await setup();for(const [handler,body,token,method] of [[review,{},'owner','GET'],[review,{},null,'POST'],[review,null,'owner','POST'],[gmail,{approval:'USER_CONFIRMED',body:'Bypass'},'owner','POST'],[gmail,{approval_id:ids.draft},'foreign','POST'],[twilio,{channel:'sms',approval:'USER_CONFIRMED'},'owner','POST']]){const r=await request(handler,body,token,method);assert.ok(r.status>=400);}assert.equal(providerCalls.length,0);assert.equal(secretCalls,0);});
test('default runtime disabled gate does not reserve or retrieve secrets',async()=>{await setup();const a=await approve();enabled=false;const r=await request(gmail,{approval_id:a.approval_id});assert.equal(r.status,503);assert.equal(providerCalls.length,0);assert.equal(secretCalls,0);assert.equal((await active.db.query('select count(*)::int n from reply_dispatches')).rows[0].n,0);});
test('unsupported price and client-forged passing report remain blocked',async()=>{await setup();const s=await request(review,{operation:'SAVE',draft_id:ids.draft,queue_item_id:ids.item,revision:1,text:'It costs $9999.',claims:[]});assert.equal(s.status,200);const r=await request(review,{operation:'CHECK',draft_id:ids.draft,result:{status:'SOURCE_SUPPORTED_REQUIRES_REVIEW'},evidence:[{basis:'source_system'}]});assert.equal(r.body.check.status,'BLOCKED');const a=await request(review,{operation:'APPROVE',check_id:r.body.check_id,review_key:r.body.check.reviewKey,snapshot_key:r.body.check.snapshotKey,coverage_reviewed:true});assert.equal(a.status,409);assert.equal(providerCalls.length,0);});
test('send success plus ingestion failure stays SENT and never repeats external send',async()=>{await setup();const a=await approve();ingestFails=true;const sent=await request(gmail,{approval_id:a.approval_id});assert.equal(sent.body.status,'SENT');assert.equal(sent.body.ingestion_pending,true);await request(gmail,{approval_id:a.approval_id});assert.equal(providerCalls.length,1);});
for(const mode of ['throw','malformed'])test(`provider ${mode} result stays UNKNOWN with no blind retry`,async()=>{await setup();const a=await approve();providerMode=mode;const r=await request(gmail,{approval_id:a.approval_id});assert.equal(r.body.status,'UNKNOWN');const replay=await request(gmail,{approval_id:a.approval_id});assert.equal(replay.body.status,'UNKNOWN');assert.equal(providerCalls.length,1);});
test('source change blocks before secrets and provider call',async()=>{await setup();const a=await approve();await active.db.exec("update messages set body_text='New conflicting context'");const r=await request(gmail,{approval_id:a.approval_id});assert.equal(r.status,409);assert.equal(providerCalls.length,0);assert.equal(secretCalls,0);});
test('WhatsApp window is checked before token retrieval',async()=>{await setup('whatsapp');await active.db.exec("update messages set sent_at=clock_timestamp()-interval '25 hours'");const a=await approve();const r=await request(twilio,{channel:'whatsapp',approval_id:a.approval_id});assert.equal(r.body.status,'FAILED');assert.equal(providerCalls.length,0);assert.equal(secretCalls,0);});
test.after(shutdown);
