import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,ids,shutdown} from './reply-fixture.mjs';
import {checkReply} from '../supabase/functions/api/_shared/reply-evidence.ts';
const save={queue_item_id:ids.item,draft_id:ids.draft,revision:0,text:'Thank you.',claims:[]};
async function checked(f){const state=await f.command('SNAPSHOT',{draft_id:ids.draft});const now=new Date().toISOString();const result=await checkReply({...state,evidenceRead:{...state.evidenceRead,readAt:now}},now);return f.command('CHECK',{draft_id:ids.draft,revision:state.draft.revision,state,result});}
async function approved(f){const c=await checked(f);return f.command('APPROVE',{check_id:c.check_id,snapshot_key:c.check.snapshotKey,review_key:c.check.reviewKey,coverage_reviewed:true});}
async function setup(){const f=await fixture();await f.command('SAVE',save);return f;}
for(const op of ['READ','WRITE'])test(`new reply tables reject authenticated ${op}`,async()=>{const f=await setup();try{await f.db.exec('reset role;set role authenticated');await assert.rejects(f.db.exec(op==='READ'?'select * from reply_checks':"insert into reply_context_state(user_id,queue_item_id,thread_id,contact_id,business_id) values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid())"),/permission denied/);}finally{await f.db.close();}});
test('browser cannot invoke privileged reply RPC or spoof actor',async()=>{const f=await setup();try{await assert.rejects(f.command('SNAPSHOT',{draft_id:ids.draft},ids.other),/not found/);await f.db.exec('reset role;set role authenticated');await assert.rejects(f.command('SNAPSHOT',{draft_id:ids.draft}),/permission denied/);}finally{await f.db.close();}});
test('actual SQL save/check/approve/reserve/begin/sent with durable replay denial',async()=>{const f=await setup();try{const a=await approved(f);const r=await f.command('RESERVE',{approval_id:a.approval_id,channel:'email'});const b=await f.command('BEGIN',{dispatch_id:r.dispatch_id,channel:'email'});assert.equal(b.payload.text,save.text);assert.equal(b.status,'SENDING');assert.equal((await f.command('BEGIN',{dispatch_id:r.dispatch_id,channel:'email'})).existing,true);assert.equal((await f.command('RESERVE',{approval_id:a.approval_id,channel:'email'})).existing,true);await f.command('FINISH',{dispatch_id:r.dispatch_id,status:'SENT',provider_id:'synthetic'});assert.equal((await f.command('STATUS',{dispatch_id:r.dispatch_id})).status,'SENT');}finally{await f.db.close();}});
test('edited/reverted draft invalidates approval and stale saves fail CAS',async()=>{const f=await setup();try{const a=await approved(f);await f.command('SAVE',{...save,revision:1,text:'Changed'});await assert.rejects(f.command('SAVE',{...save,revision:1}),/revision changed/);await f.command('SAVE',{...save,revision:2});await assert.rejects(f.command('RESERVE',{approval_id:a.approval_id,channel:'email'}),/state changed/);}finally{await f.db.close();}});
test('new inbound or changed source invalidates prior check through real trigger',async()=>{for(const sql of [`update messages set body_text='Changed' where id='${ids.message}'`,`insert into messages select gen_random_uuid(),user_id,thread_id,contact_id,direction,channel,from_identifier,'New information',clock_timestamp(),subject,null,references_ids,gmail_account_id,twilio_number_id,provider,provider_message_id,to_identifiers,cc_identifiers,headers from messages where id='${ids.message}'`]){const f=await setup();try{const a=await approved(f);await f.db.exec(sql);await assert.rejects(f.command('RESERVE',{approval_id:a.approval_id,channel:'email'}),/state changed/);}finally{await f.db.close();}}});
test('source change after reservation blocks BEGIN without provider permission',async()=>{const f=await setup();try{const a=await approved(f),r=await f.command('RESERVE',{approval_id:a.approval_id,channel:'email'});await f.db.exec(`update messages set body_text='Updated' where id='${ids.message}'`);await assert.rejects(f.command('BEGIN',{dispatch_id:r.dispatch_id,channel:'email'}),/state changed/);}finally{await f.db.close();}});
test('human evidence is linked to exact owned source revision and excerpt',async()=>{const f=await fixture();try{let s=await f.command('SAVE',{...save,text:'It costs $1250.',claims:[{id:'price',kind:'price',start:9,end:14,quote:'$1250',factKey:'quote:q1:total',value:'USD:125000',evidenceIds:[]}]});const src=s.sources[0];const evidence={draft_id:ids.draft,revision:1,message_id:ids.message,source_hash:src.hash,kind:'price',fact_key:'quote:q1:total',value:'USD:125000',start:13,end:18,excerpt:'$1250',valid_until:new Date(Date.now()+3600000).toISOString(),reviewed:true};await assert.rejects(f.command('EVIDENCE',{...evidence,source_hash:'fake'}),/changed/);const e=await f.command('EVIDENCE',evidence);s=await f.command('SAVE',{...save,revision:1,text:'It costs $1250.',claims:[{id:'price',kind:'price',start:9,end:14,quote:'$1250',factKey:'quote:q1:total',value:'USD:125000',evidenceIds:[e.evidence_id]}]});const c=await checked(f);assert.equal(c.check.status,'SOURCE_SUPPORTED_REQUIRES_REVIEW');await f.command('REVOKE',{draft_id:ids.draft,revision:2,evidence_id:e.evidence_id});assert.equal((await checked(f)).check.status,'BLOCKED');}finally{await f.db.close();}});
test('unknown outcome cannot be resumed or replayed as a new send',async()=>{const f=await setup();try{const a=await approved(f),r=await f.command('RESERVE',{approval_id:a.approval_id,channel:'email'});await f.command('BEGIN',{dispatch_id:r.dispatch_id,channel:'email'});await f.command('FINISH',{dispatch_id:r.dispatch_id,status:'UNKNOWN'});const replay=await f.command('RESERVE',{approval_id:a.approval_id,channel:'email'});assert.equal(replay.existing,true);assert.equal(replay.status,'UNKNOWN');}finally{await f.db.close();}});


test('new approval cannot bypass unresolved delivery in the same context',async()=>{const f=await setup();try{const a=await approved(f),r=await f.command('RESERVE',{approval_id:a.approval_id,channel:'email'});await f.command('BEGIN',{dispatch_id:r.dispatch_id,channel:'email'});await f.command('FINISH',{dispatch_id:r.dispatch_id,status:'UNKNOWN'});await f.command('SAVE',{...save,revision:1});await assert.rejects(approved(f),/outcome unresolved/);}finally{await f.db.close();}});
test('cancel reports actual status and cannot pretend an in-progress send stopped',async()=>{const f=await setup();try{const a=await approved(f),r=await f.command('RESERVE',{approval_id:a.approval_id,channel:'email'});await f.command('BEGIN',{dispatch_id:r.dispatch_id,channel:'email'});assert.equal((await f.command('CANCEL',{dispatch_id:r.dispatch_id})).status,'SENDING');}finally{await f.db.close();}});
test('missing revision fails CAS and missing source hash cannot record evidence',async()=>{const f=await setup();try{await assert.rejects(f.command('SAVE',{...save,revision:null}),/revision changed/);await assert.rejects(f.command('EVIDENCE',{draft_id:ids.draft,revision:1,reviewed:true,message_id:ids.message}),/source missing/);}finally{await f.db.close();}});
test('same-user foreign-client source is omitted and blocks completeness',async()=>{const f=await setup();try{await f.db.exec(`update messages set contact_id='${ids.other}' where id='${ids.message}'`);const s=await f.command('SNAPSHOT',{draft_id:ids.draft});assert.equal(s.sources.length,0);assert.equal(s.evidenceRead.complete,false);assert.equal((await checked(f)).check.status,'BLOCKED');}finally{await f.db.close();}});
test('header injection in stored threading headers blocks the snapshot',async()=>{const f=await setup();try{await f.db.exec("update messages set rfc822_message_id=E'evil\\r\\nBcc: other@example.invalid'");await assert.rejects(f.command('SNAPSHOT',{draft_id:ids.draft}),/headers/);}finally{await f.db.close();}});
test('source account mismatch is excluded and blocks complete review',async()=>{const f=await setup();try{await f.db.exec(`update messages set gmail_account_id='${ids.other}'`);const state=await f.command('SNAPSHOT',{draft_id:ids.draft});assert.equal(state.sources.length,0);assert.equal(state.evidenceRead.complete,false);}finally{await f.db.close();}});
test('source provider identity changes invalidate an approved source revision',async()=>{const f=await setup();try{const a=await approved(f);await f.db.exec("update messages set provider_message_id='replacement-source'");await assert.rejects(f.command('RESERVE',{approval_id:a.approval_id,channel:'email'}),/state changed/);}finally{await f.db.close();}});
test.after(shutdown);
